# Generated by Django 4.2.5 on 2023-09-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_url', models.TextField(max_length=100)),
                ('categories', models.TextField(max_length=100)),
            ],
        ),
    ]
