# Generated by Django 4.2.5 on 2023-09-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraping', '0002_formdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='categories',
        ),
    ]
